<#import "../common.ftl" as c />
<@c.AutoGeneratedWarning />
package com.linkedin.dagli.transformer;

import com.linkedin.dagli.annotation.equality.ValueEquality;
import com.linkedin.dagli.preparer.PreparerContext;
import com.linkedin.dagli.preparer.TrivialPreparer${arity};
import com.linkedin.dagli.preparer.Preparer${arity};
import com.linkedin.dagli.producer.Producer;
import java.util.Objects;

<#assign constantResultTransformationClassSignature><@c.ConstantResultTransformation arity /></#assign>
<#assign preparedConstantResultTransformationClassSignature><@c.PreparedConstantResultTransformation arity /></#assign>

/**
 * A trivial implementation of a preparable transformer that ignores its inputs and provides a constant result.
 *
<@c.GenericInputTypesJavadoc arity />
 *
 * @param <R> the type of the constant result that will be returned by the prepared transformer.
 */
@ValueEquality
public final class <@c.ConstantResultTransformation arity /> extends
    <@c.AbstractPreparableTransformer arity preparedConstantResultTransformationClassSignature constantResultTransformationClassSignature />
    implements ConstantResultTransformation<R, <@c.ConstantResultTransformation arity />>{
  private static final long serialVersionUID = 1;

  // the object instance that will be the constant result of this transformer
  private R _resultForNewData = null;
  private R _resultForPreparationData = null;

  /**
   * Creates a new constant result preparable transformer that will ignore its inputs and will always has a null result.
   */
  public ConstantResultTransformation${arity}() { }

  @Override
  protected boolean hasAlwaysConstantResult() {
    return true;
  }

  @Override
  protected boolean hasIdempotentPreparer() {
    return true;
  }

  /**
   * Returns a copy of this transformer that will always have the specified constant result object for both new and
   * preparation data.  Note that this exact object will be returned every time the transformer is applied (and not a
   * clone).
   *
   * @param result the result that will always be returned by this transformer
   * @return a copy of this transformer that will always have the specified constant result
   */
  public <@c.ConstantResultTransformation arity /> withResult(R result) {
    return clone(c -> {
      c._resultForNewData = result;
      c._resultForPreparationData = result;
    });
  }

  /**
   * Returns a copy of this transformer that will always have the specified constant result object for preparation data.
   * Note that this exact object will be returned every time the transformer is applied (and not a clone).
   *
   * @param result the result that will always be returned by this transformer for preparation data
   * @return a copy of this transformer that will always have the specified constant result
   */
  public <@c.ConstantResultTransformation arity /> withResultForPreparationData(R result) {
    return clone(c -> {
      c._resultForPreparationData = result;
    });
  }

  /**
   * Returns a copy of this transformer that will always have the specified constant result object for new data.
   * Note that this exact object will be returned every time the transformer is applied (and not a clone).
   *
   * @param result the result that will always be returned by this transformer for new data
   * @return a copy of this transformer that will always have the specified constant result
   */
  public <@c.ConstantResultTransformation arity /> withResultForNewData(R result) {
    return clone(c -> {
      c._resultForNewData = result;
    });
  }

  /**
   * @return the object instance that will be produced by this transformer for all new examples.
   */
  public R getResultForNewData() {
    return _resultForNewData;
  }

  /**
   * @return the object instance that will be produced by this transformer for all preparation examples.
   */
  public R getResultForPreparationData() {
    return _resultForPreparationData;
  }

  @Override
  protected <@c.Preparer arity preparedConstantResultTransformationClassSignature /> getPreparer(PreparerContext context) {
    <@c.PreparedConstantResultTransformation arity /> resultForPrepData =
      new <@c.PreparedConstantResultTransformation arity />(_resultForPreparationData);
    return _resultForPreparationData == _resultForNewData ? new TrivialPreparer${arity}<>(resultForPrepData)
        : new TrivialPreparer${arity}<>(resultForPrepData,
            new <@c.PreparedConstantResultTransformation arity />(_resultForNewData));
  }

  <#-- Raise the visibility of all the withInputX(...) methods to "public" -->
  <#list 1..arity as index>
  <#if (arity > 1)>@Override</#if>
  public <@c.ConstantResultTransformation arity /> withInput<#if (arity > 1)>${c.InputSuffix(index)}</#if>(Producer<? extends ${c.InputGenericArgument(index)}> input${c.inputLetters[index]}) {
    return super.withInput${c.InputSuffix(index)}(input${c.inputLetters[index]});
  }
  </#list>

  @Override
  public String getName() {
    return "ConstantResultTransformation${arity}(" + (Objects.equals(_resultForNewData, _resultForPreparationData) ? _resultForNewData
        : ("prep = " + _resultForPreparationData + ", new = " + _resultForNewData)) + ")";
  }

  /**
   * A trivial implementation of a prepared transformer that ignores its inputs and provides a constant result.
   *
  <@c.GenericInputTypesJavadoc arity />
   * @param <R> the type of the constant result that will be returned by the transformer.
   */
  @ValueEquality
  public static final class Prepared<<@c.InputGenericArguments arity />, R>
      extends <@c.AbstractPreparedTransformer arity preparedConstantResultTransformationClassSignature />
      implements ConstantResultTransformation.Prepared<R, <@c.PreparedConstantResultTransformation arity />> {
    private static final long serialVersionUID = 1;

    // the object instance that will be the constant result of this transformer
    private R _result = null;

    @Override
    protected boolean hasAlwaysConstantResult() {
      return true;
    }

    /**
     * Creates a new trivial prepared transformer that will ignore its inputs and always have a null result.
     */
    public Prepared() { }

    /**
     * Creates a new trivial prepared transformer that will ignore its inputs and always have the given result.
     *
     * @param result the result to be "produced"
     */
    public Prepared(R result) {
      _result = result;
    }

    /**
     * Returns a copy of this transformer that will always have the specified constant result object.  Note that this
     * exact result object will be returned every time the transformer is applied (and not a clone).
     *
     * @param result the result that will always be returned when applying the transformer
     * @return a copy of this transformer that will always have the specified constant result
     */
    public <@c.PreparedConstantResultTransformation arity /> withResult(R result) {
      return clone(c -> c._result = result);
    }

    /**
     * Gets the object instance that will be produced by this transformer for all inputs.
     *
     * @return the object instance that will be produced by this transformer for all inputs.
     */
    public R getResult() {
      return _result;
    }

    @Override
    public R apply(<@c.InputSuffixedParameters "value" arity />) {
      return _result;
    }

    <#-- Raise the visibility of all the withInputX(...) methods to "public" -->
    <#list 1..arity as index>
    <#if (arity > 1)>@Override</#if>
    public <@c.PreparedConstantResultTransformation arity /> withInput<#if (arity > 1)>${c.InputSuffix(index)}</#if>(Producer<? extends ${c.InputGenericArgument(index)}> input${c.inputLetters[index]}) {
      return super.withInput${c.InputSuffix(index)}(input${c.inputLetters[index]});
    }
    </#list>

    @Override
    public String getName() {
      return "ConstantResultTransformation${arity}.Prepared(" + _result + ")";
    }
  }
}
