<#import "../common.ftl" as c />
<@c.AutoGeneratedWarning />
package com.linkedin.dagli.transformer;

import com.linkedin.dagli.transformer.internal.Transformer${arity}InternalAPI;

<#assign subclass>? extends <@c.Transformer arity /></#assign>
public interface <@c.Transformer arity /> extends Transformer<R> {

  @Override
  <@c.TransformerInternalAPI arity subclass /> internalAPI();


  <#-- Only make withInput function if arity is 1 -->
  <#-- <#if (arity == 1)>
    <@c.Transformer arity /> withInput(<@c.InputProducerList arity />);
  </#if> -->
}
