package com.linkedin.dagli.generator.internal;

import com.linkedin.dagli.generator.Generator;
import com.linkedin.dagli.producer.internal.RootProducerInternalAPI;


/**
 * The internal API interface for generators.  Dagli clients should not use this interface directly as it is subject to
 * breaking changes in even minor revisions of the library.
 *
 * @param <R> the type generated by the generator
 * @param <S> the concrete, derived type of the generator
 */
public interface GeneratorInternalAPI<R, S extends Generator<R>> extends RootProducerInternalAPI<R, S> { }
